int	ft_isalpha(int c);
int	ft_isdigit(int c);
int	ft_strlen(char *s);
int	ft_isalnum(int c);
int	ft_isascii(int c);
int	ft_isprint(int c);
unsigned int	ft_strlcpy(char *dest, char *src, unsigned int size);
int	ft_toupper(int c);
int	ft_tolower(int c);
int	ft_atoi(char *str);
char	*ft_strchr(const char *s, int c);
