# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cvidot <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/12 11:13:00 by cvidot            #+#    #+#              #
#    Updated: 2023/01/12 11:36:26 by cvidot           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = ft_atoi.c, ft_isalnum.c, ft_isalpha.c, ft_isascii.c, ft_isidgit.c, ft_isprint.c, ft_strchr.c, ft_strlcpy.c, ft_strlen.c, ft_tolwer.c, ft_toupper.c

CFLAGS = -Wall -Werror -Wextra


